SELENIUM_URL: str = ""

MYSQL_USERNAME: str = ''
MYSQL_PASSWORD: str = ''
MYSQL_DATABASE_NAME: str = ""
MYSQL_PORT: int = 3308
MYSQL_HOST_URL: str = ''

PA_MYSQL_USERNAME: str = ''
PA_MYSQL_PASSWORD: str = ''
PA_MYSQL_HOST_URL: str = ''
PA_MYSQL_PORT: int = 3306
PA_MYSQL_DATABASE_NAME: str = PA_MYSQL_USERNAME + "$" + MYSQL_DATABASE_NAME
